# Generated by Django 3.2.9 on 2021-12-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabecagado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nascimento', models.DateField()),
                ('observacoes', models.TextField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='vacinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('febre_aftosa', models.BooleanField()),
                ('brucelose', models.BooleanField()),
                ('clostridioses', models.BooleanField()),
                ('botulismo', models.BooleanField()),
                ('leptospirose', models.BooleanField()),
                ('raiva', models.BooleanField()),
                ('ibr_bvd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='matriz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gestacoes', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('observacoes', models.TextField(max_length=280)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_medica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.JSONField()),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
        migrations.CreateModel(
            name='boi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nascimento', models.DateField()),
                ('observacoes', models.TextField(max_length=280)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
    ]
