# Generated by Django 3.2.9 on 2021-12-11 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brinco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cor_nome', models.TextField(max_length=16)),
                ('cor_HEX', models.TextField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='cabecagado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.BooleanField()),
                ('valor', models.FloatField()),
                ('envolvido', models.TextField(max_length=32)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vacinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('febre_aftosa', models.BooleanField(default=False)),
                ('brucelose', models.BooleanField(default=False)),
                ('clostridioses', models.BooleanField(default=False)),
                ('botulismo', models.BooleanField(default=False)),
                ('leptospirose', models.BooleanField(default=False)),
                ('raiva', models.BooleanField(default=False)),
                ('ibr_bvd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='matriz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_etiqueta', models.IntegerField()),
                ('gestacoes', models.IntegerField(default=0)),
                ('nascimento', models.DateField(null=True)),
                ('observacoes', models.TextField(blank=True, max_length=280, null=True)),
                ('esta_vivo', models.BooleanField(default=True)),
                ('morte', models.DateField(null=True)),
                ('causa_mortis', models.TextField(max_length=30, null=True)),
                ('brinco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.brinco')),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_medica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pesos', models.TextField(max_length=1024, null=True)),
                ('datas', models.TextField(max_length=1024, null=True)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
        migrations.CreateModel(
            name='cria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_etiqueta', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('sexo', models.BooleanField()),
                ('observacoes', models.TextField(blank=True, max_length=280, null=True)),
                ('esta_vivo', models.BooleanField(default=True)),
                ('morte', models.DateField(null=True)),
                ('causa_mortis', models.TextField(max_length=30, null=True)),
                ('brinco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.brinco')),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.matriz')),
            ],
        ),
        migrations.CreateModel(
            name='cabeca_transacionada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabecagado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.transacao')),
            ],
        ),
        migrations.CreateModel(
            name='boi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nascimento', models.DateField(null=True)),
                ('observacoes', models.TextField(blank=True, max_length=280, null=True)),
                ('esta_vivo', models.BooleanField(default=True)),
                ('n_etiqueta', models.IntegerField(null=True)),
                ('morte', models.DateField(null=True)),
                ('causa_mortis', models.TextField(max_length=30, null=True)),
                ('brinco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.brinco')),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
    ]
