# Generated by Django 3.2.9 on 2021-12-14 12:16

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brinco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cor_nome', models.CharField(max_length=16, unique=True)),
                ('cor', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='cabecagado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_etiqueta', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=5)),
                ('observacoes', models.TextField(blank=True, max_length=280, null=True)),
                ('esta_vivo', models.BooleanField(default=True)),
                ('vendido', models.BooleanField(default=False)),
                ('morte', models.DateField(blank=True, null=True)),
                ('causa_mortis', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('Boi', 'Touro'), ('Vaca', 'Vaca'), ('Bezerro', 'Bezerro')], max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brinco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.brinco')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_medica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pesos_timeseries', models.CharField(default='', max_length=2048, null=True)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
        migrations.CreateModel(
            name='transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.BooleanField()),
                ('valor', models.FloatField()),
                ('envolvido', models.CharField(max_length=32)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vacinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('febre_aftosa', models.BooleanField(default=False)),
                ('brucelose', models.BooleanField(default=False)),
                ('clostridioses', models.BooleanField(default=False)),
                ('botulismo', models.BooleanField(default=False)),
                ('leptospirose', models.BooleanField(default=False)),
                ('raiva', models.BooleanField(default=False)),
                ('ibr_bvd', models.BooleanField(default=False)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.ficha_medica')),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='matriz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
        migrations.CreateModel(
            name='cria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.matriz')),
            ],
        ),
        migrations.CreateModel(
            name='cabeca_transacionada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabecagado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criacao.transacao')),
            ],
        ),
        migrations.CreateModel(
            name='boi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabecagado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado')),
            ],
        ),
    ]
