# Generated by Django 3.2.9 on 2021-12-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_medica',
            name='peso',
        ),
        migrations.AddField(
            model_name='cria',
            name='matriz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criacao.matriz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_medica',
            name='datas',
            field=models.TextField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_medica',
            name='pesos',
            field=models.TextField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
