# Generated by Django 3.2.9 on 2021-12-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criacao', '0002_auto_20211209_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='cria',
            name='cabecagado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='criacao.cabecagado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boi',
            name='observacoes',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='cria',
            name='observacoes',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='observacoes',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='botulismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='brucelose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='clostridioses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='febre_aftosa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='ibr_bvd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='leptospirose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='raiva',
            field=models.BooleanField(default=False),
        ),
    ]
