# Generated by Django 3.2.7 on 2021-12-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criacao', '0003_transacao_gados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='tags',
        ),
    ]
