# Generated by Django 3.2.9 on 2021-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criacao', '0004_alter_boi_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='observacoes',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='cria',
            name='observacoes',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='datas',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='pesos',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='gestacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='observacoes',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
